# Generated by Django 4.2.6 on 2023-11-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('ID_c', models.AutoField(primary_key=True, serialize=False)),
                ('Comentario', models.TextField(null=True, verbose_name='Comentario')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
    ]
